import React, { useEffect, useState } from 'react';
import { api } from '../services/api_client';
import {
  Download,
  ShieldCheck,
  FileText,
  AlertTriangle,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Printer,
  BarChart2
} from 'lucide-react';

const severityStyle = (s: string) => {
  switch (s?.toLowerCase()) {
    case 'critical': return 'bg-rose-100 text-rose-700 dark:bg-rose-950/30 dark:text-rose-400';
    case 'high':     return 'bg-amber-100 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400';
    case 'medium':   return 'bg-blue-100 text-blue-700 dark:bg-blue-950/30 dark:text-blue-400';
    default:         return 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400';
  }
};

const scoreColor = (pct: number) => {
  if (pct >= 80) return 'text-emerald-600 dark:text-emerald-400';
  if (pct >= 50) return 'text-amber-600 dark:text-amber-400';
  return 'text-rose-600 dark:text-rose-400';
};

const generateHTMLReport = (analysis: any) => {
  const score = Math.round((analysis.scores?.[0]?.overall_score || 0) * 100);
  const risk  = (analysis.scores?.[0]?.risk_score ?? 0) >= 0.7 ? 'High'
              : (analysis.scores?.[0]?.risk_score ?? 0) >= 0.35 ? 'Medium' : 'Low';
  const findings = analysis.findings || [];
  const date = new Date(analysis.created_at).toLocaleString();

  const findingsRows = findings.map((f: any) => `
    <tr>
      <td><span class="badge ${f.severity?.toLowerCase()}">${f.severity}</span></td>
      <td>${f.category}</td>
      <td>${f.article}</td>
      <td>${f.explanation}</td>
      <td>${Math.round(f.confidence * 100)}%</td>
      <td>${f.suggested_fix}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>PolicyGuard AI — Compliance Audit Report</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1e293b; margin: 40px; font-size: 13px; }
    h1 { color: #1e3d6b; font-size: 22px; margin-bottom: 4px; }
    h2 { color: #1e3d6b; font-size: 15px; border-bottom: 2px solid #dce4f2; padding-bottom: 6px; margin-top: 28px; }
    .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
    .score-box { display: inline-block; padding: 12px 24px; border-radius: 12px; background: #f0f4f9; border: 1px solid #dce4f2; text-align: center; margin-right: 16px; }
    .score-box .num { font-size: 28px; font-weight: 800; }
    .green { color: #059669; } .amber { color: #d97706; } .red { color: #e11d48; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th { background: #f0f4f9; text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #475569; }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
    .badge { padding: 2px 8px; border-radius: 99px; font-size: 11px; font-weight: 600; }
    .badge.critical { background: #ffe4e6; color: #be123c; }
    .badge.high     { background: #fef3c7; color: #92400e; }
    .badge.medium   { background: #dbeafe; color: #1d4ed8; }
    .badge.low      { background: #f1f5f9; color: #475569; }
    .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>🛡️ PolicyGuard AI — Compliance Audit Report</h1>
  <div class="meta">Generated: ${date} &nbsp;|&nbsp; Framework: <strong>${analysis.framework}</strong> &nbsp;|&nbsp; Analysis ID: ${analysis.id}</div>

  <h2>Executive Summary</h2>
  <div>
    <div class="score-box">
      <div class="num ${score >= 80 ? 'green' : score >= 50 ? 'amber' : 'red'}">${score}%</div>
      <div>Overall Score</div>
    </div>
    <div class="score-box">
      <div class="num ${risk === 'Low' ? 'green' : risk === 'Medium' ? 'amber' : 'red'}">${risk}</div>
      <div>Risk Level</div>
    </div>
    <div class="score-box">
      <div class="num red">${findings.length}</div>
      <div>Violations Found</div>
    </div>
  </div>

  <h2>Violations & Findings Detail</h2>
  ${findings.length === 0
    ? '<p style="color:#059669;font-weight:600">✅ No violations detected. Policy is fully compliant.</p>'
    : `<table>
        <thead><tr>
          <th>Severity</th><th>Category</th><th>Article</th>
          <th>Explanation</th><th>Confidence</th><th>Suggested Fix</th>
        </tr></thead>
        <tbody>${findingsRows}</tbody>
       </table>`}

  <div class="footer">
    Report generated by PolicyGuard AI Compliance Platform &nbsp;·&nbsp; ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;
};

export const Reports: React.FC = () => {
  const [analyses, setAnalyses] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true);
        const data = await api.getAnalyses();
        setAnalyses(Array.isArray(data) ? data : [data]);
      } catch (err) {
        console.error('Failed to load analyses:', err);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const handlePrint = (analysis: any) => {
    const html = generateHTMLReport(analysis);
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  };

  const handleDownloadJSON = (analysis: any) => {
    const blob = new Blob([JSON.stringify(analysis, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `audit_${analysis.framework}_${analysis.id.slice(0, 8)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex-grow flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div>
        <h2 className="text-3xl font-bold tracking-tight text-slate-800 dark:text-white">Audit Reports Registry</h2>
        <p className="text-slate-500 dark:text-slate-400 mt-1">View, export, and print compliance audit reports for all analysed policy documents.</p>
      </div>

      {analyses.length === 0 ? (
        <div className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl p-16 text-center shadow-sm">
          <FileText className="h-16 w-16 text-slate-300 dark:text-slate-700 mx-auto mb-4" />
          <h4 className="font-bold text-slate-700 dark:text-slate-300">No reports yet</h4>
          <p className="text-slate-400 text-xs mt-1 max-w-xs mx-auto">
            Run a compliance audit from the <strong>Document Analysis</strong> page. Reports will appear here automatically.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {analyses.map((analysis) => {
            const score = Math.round((analysis.scores?.[0]?.overall_score || 0) * 100);
            const risk  = (analysis.scores?.[0]?.risk_score ?? 0) >= 0.7 ? 'High'
                        : (analysis.scores?.[0]?.risk_score ?? 0) >= 0.35 ? 'Medium' : 'Low';
            const isOpen = expanded === analysis.id;

            return (
              <div key={analysis.id} className="bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 rounded-2xl shadow-sm overflow-hidden">
                {/* Header Row */}
                <div
                  onClick={() => setExpanded(isOpen ? null : analysis.id)}
                  className="p-5 flex items-center justify-between cursor-pointer hover:bg-slate-50/50 dark:hover:bg-slate-800/10 transition-colors"
                >
                  <div className="flex items-center gap-4">
                    <div className="h-10 w-10 rounded-xl bg-primary-50 dark:bg-primary-900/20 flex items-center justify-center">
                      <ShieldCheck className="h-5 w-5 text-primary-600" />
                    </div>
                    <div>
                      <p className="font-bold text-slate-800 dark:text-slate-100 text-sm">
                        {analysis.framework} Compliance Audit
                      </p>
                      <p className="text-xs text-slate-400 mt-0.5">
                        {new Date(analysis.created_at).toLocaleString()} &nbsp;·&nbsp; {analysis.findings?.length || 0} findings
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-4">
                    {/* Score badge */}
                    <div className="text-center hidden sm:block">
                      <span className={`text-2xl font-extrabold ${scoreColor(score)}`}>{score}%</span>
                      <p className="text-xs text-slate-400">Score</p>
                    </div>

                    {/* Risk badge */}
                    <span className={`px-2.5 py-1 rounded-full text-xs font-bold hidden sm:inline-block ${
                      risk === 'High'   ? 'bg-rose-100 text-rose-700 dark:bg-rose-950/30 dark:text-rose-400' :
                      risk === 'Medium' ? 'bg-amber-100 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400' :
                                         'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400'
                    }`}>
                      {risk} Risk
                    </span>

                    {/* Actions */}
                    <div className="flex items-center gap-1" onClick={e => e.stopPropagation()}>
                      <button
                        onClick={() => handlePrint(analysis)}
                        title="Print / Save as PDF"
                        className="p-2 text-slate-400 hover:text-primary-600 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"
                      >
                        <Printer className="h-4 w-4" />
                      </button>
                      <button
                        onClick={() => handleDownloadJSON(analysis)}
                        title="Export as JSON"
                        className="p-2 text-slate-400 hover:text-primary-600 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors"
                      >
                        <Download className="h-4 w-4" />
                      </button>
                    </div>

                    {isOpen ? <ChevronUp className="h-5 w-5 text-slate-400" /> : <ChevronDown className="h-5 w-5 text-slate-400" />}
                  </div>
                </div>

                {/* Expanded Detail */}
                {isOpen && (
                  <div className="border-t border-slate-100 dark:border-slate-800 p-6 space-y-6">
                    {/* Score breakdown */}
                    {analysis.scores?.[0] && (
                      <div>
                        <h4 className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider text-slate-400 mb-3">
                          <BarChart2 className="h-4 w-4" /> Score Breakdown
                        </h4>
                        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                          {[
                            { label: 'Overall',     val: analysis.scores[0].overall_score },
                            { label: 'Framework',   val: analysis.scores[0].framework_score },
                            { label: 'Transparency',val: analysis.scores[0].transparency_score },
                            { label: 'Consent',     val: analysis.scores[0].consent_score },
                            { label: 'Security',    val: analysis.scores[0].security_score },
                            { label: 'Retention',   val: analysis.scores[0].retention_score },
                          ].filter(m => m.val != null).map(m => (
                            <div key={m.label} className="bg-slate-50 dark:bg-slate-950 rounded-xl p-3 text-center border border-slate-100 dark:border-slate-800">
                              <p className={`text-xl font-extrabold ${scoreColor(Math.round(m.val * 100))}`}>
                                {Math.round(m.val * 100)}%
                              </p>
                              <p className="text-xs text-slate-400 mt-0.5">{m.label}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Findings table */}
                    <div>
                      <h4 className="flex items-center gap-2 font-bold text-xs uppercase tracking-wider text-slate-400 mb-3">
                        <AlertTriangle className="h-4 w-4" /> Violations Found ({analysis.findings?.length || 0})
                      </h4>

                      {(!analysis.findings || analysis.findings.length === 0) ? (
                        <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 text-sm">
                          <CheckCircle className="h-5 w-5" />
                          <span className="font-semibold">No violations — fully compliant!</span>
                        </div>
                      ) : (
                        <div className="overflow-x-auto rounded-xl border border-slate-100 dark:border-slate-800">
                          <table className="w-full text-sm border-collapse">
                            <thead>
                              <tr className="bg-slate-50 dark:bg-slate-950 text-xs font-semibold uppercase tracking-wider text-slate-400">
                                <th className="py-3 px-4 text-left">Severity</th>
                                <th className="py-3 px-4 text-left">Category</th>
                                <th className="py-3 px-4 text-left">Article</th>
                                <th className="py-3 px-4 text-left">Explanation</th>
                                <th className="py-3 px-4 text-left">Confidence</th>
                              </tr>
                            </thead>
                            <tbody>
                              {analysis.findings.map((f: any) => (
                                <tr key={f.id} className="border-t border-slate-50 dark:border-slate-800/40 hover:bg-slate-50/40 dark:hover:bg-slate-800/10">
                                  <td className="py-3 px-4">
                                    <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${severityStyle(f.severity)}`}>
                                      {f.severity}
                                    </span>
                                  </td>
                                  <td className="py-3 px-4 font-medium text-slate-700 dark:text-slate-300">{f.category}</td>
                                  <td className="py-3 px-4 text-slate-400 text-xs">{f.article}</td>
                                  <td className="py-3 px-4 text-slate-600 dark:text-slate-400 max-w-xs">{f.explanation}</td>
                                  <td className="py-3 px-4 text-slate-500 font-semibold">{Math.round(f.confidence * 100)}%</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      )}
                    </div>

                    {/* Generate Report button */}
                    <div className="pt-2 flex justify-end gap-3">
                      <button
                        onClick={() => handleDownloadJSON(analysis)}
                        className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition-all"
                      >
                        <Download className="h-4 w-4" />
                        Export JSON
                      </button>
                      <button
                        onClick={() => handlePrint(analysis)}
                        className="flex items-center gap-2 px-5 py-2 text-sm font-semibold bg-primary-600 hover:bg-primary-500 text-white rounded-lg shadow-lg shadow-primary-700/10 transition-all"
                      >
                        <Printer className="h-4 w-4" />
                        Generate PDF Report
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
